/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.Curso;
import Modelo.Constantes;
import javax.swing.JOptionPane;

public class EliminaCursoPorCod extends javax.swing.JFrame {

    /**
     * Creates new form Cursos
     */
    public EliminaCursoPorCod() {
        initComponents();
    }

    public void limpiarCodCurso() {
        this.txtCodCurso.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodCurso = new javax.swing.JTextField();
        btnEliminarCurso = new javax.swing.JButton();
        jlCamposVacios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Eliminación de curso por código");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Código del curso");

        btnEliminarCurso.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEliminarCurso.setForeground(new java.awt.Color(51, 51, 255));
        btnEliminarCurso.setText("Eliminar");
        btnEliminarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCursoMouseClicked(evt);
            }
        });
        btnEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursoActionPerformed(evt);
            }
        });

        jlCamposVacios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCamposVacios.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jlCamposVacios, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCamposVacios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
        if (txtCodCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Para continuar, ingrese un codigo a eliminar");
        } else {
            Curso cu = new Curso();
            int cod = 0;

            try {
                cod = Integer.parseInt(txtCodCurso.getText());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "El codigo de curso debe ser numerico", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            int respuesta = cu.consultarCursoPorCodigo(cod);

            if (respuesta != Constantes.EXITO) {
                JOptionPane.showMessageDialog(this, "Curso no existe", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar el curso "
                        + cu.getNombreCurso() + "?", "Confirmación",
                        JOptionPane.YES_NO_OPTION);

                if (resp == JOptionPane.YES_OPTION) {
                    resp = cu.eliminarCurso(cod);

                    if (respuesta == Constantes.EXITO) {
                        JOptionPane.showMessageDialog(this, "Elimincacion de curso exitosa", "Error",
                                JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "Eliminacion de curso fallida", "Error",
                        JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }

    }//GEN-LAST:event_btnEliminarCursoActionPerformed

    private void btnEliminarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCursoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEliminarCursoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlCamposVacios;
    private javax.swing.JTextField txtCodCurso;
    // End of variables declaration//GEN-END:variables

}
