/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

public class FrmPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public FrmPantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menListarProfesor = new javax.swing.JMenuItem();
        menInsertarProfersor = new javax.swing.JMenuItem();
        menActualizarProfesor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menListadoEstudiantes = new javax.swing.JMenuItem();
        menInsertarEstudiantes = new javax.swing.JMenuItem();
        menActualizarEstudiantes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menListadoCursos = new javax.swing.JMenuItem();
        menInsertarCursos = new javax.swing.JMenuItem();
        menActualizarCursos = new javax.swing.JMenuItem();
        menAsignarCursoProfesor = new javax.swing.JMenuItem();
        menListaoCursosProfesores = new javax.swing.JMenuItem();
        menMatricularEstudiantes = new javax.swing.JMenuItem();
        menCursoEstudiantes = new javax.swing.JMenuItem();
        menEstadisticaCurso = new javax.swing.JMenuItem();
        menNotasCurso = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menListadoInstituto = new javax.swing.JMenuItem();
        menInsertarInstituto = new javax.swing.JMenuItem();
        menActualizarInstituto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("Profesores");

        menListarProfesor.setText("Listado");
        menListarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarProfesorActionPerformed(evt);
            }
        });
        jMenu1.add(menListarProfesor);

        menInsertarProfersor.setText("Insertar");
        menInsertarProfersor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInsertarProfersorActionPerformed(evt);
            }
        });
        jMenu1.add(menInsertarProfersor);

        menActualizarProfesor.setText("Actualizar");
        menActualizarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menActualizarProfesorActionPerformed(evt);
            }
        });
        jMenu1.add(menActualizarProfesor);

        menuBar.add(jMenu1);

        jMenu2.setText("Estudiantes");

        menListadoEstudiantes.setText("Listado");
        menListadoEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListadoEstudiantesActionPerformed(evt);
            }
        });
        jMenu2.add(menListadoEstudiantes);

        menInsertarEstudiantes.setText("Insertar");
        menInsertarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInsertarEstudiantesActionPerformed(evt);
            }
        });
        jMenu2.add(menInsertarEstudiantes);

        menActualizarEstudiantes.setText("Actualizar");
        menActualizarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menActualizarEstudiantesActionPerformed(evt);
            }
        });
        jMenu2.add(menActualizarEstudiantes);

        menuBar.add(jMenu2);

        jMenu3.setText("Cursos");

        menListadoCursos.setText("Listado");
        menListadoCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListadoCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menListadoCursos);

        menInsertarCursos.setText("Insertar");
        menInsertarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInsertarCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menInsertarCursos);

        menActualizarCursos.setText("Actualizar");
        menActualizarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menActualizarCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menActualizarCursos);

        menAsignarCursoProfesor.setText("Asignar curso a Profesor");
        menAsignarCursoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAsignarCursoProfesorActionPerformed(evt);
            }
        });
        jMenu3.add(menAsignarCursoProfesor);

        menListaoCursosProfesores.setText("Listado Cursos y Profesores");
        menListaoCursosProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListaoCursosProfesoresActionPerformed(evt);
            }
        });
        jMenu3.add(menListaoCursosProfesores);

        menMatricularEstudiantes.setText("Matricular Estudiantes");
        menMatricularEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menMatricularEstudiantesActionPerformed(evt);
            }
        });
        jMenu3.add(menMatricularEstudiantes);

        menCursoEstudiantes.setText("Listado Estudiantes por Curso");
        menCursoEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCursoEstudiantesActionPerformed(evt);
            }
        });
        jMenu3.add(menCursoEstudiantes);

        menEstadisticaCurso.setText("Estadisticas Curso");
        menEstadisticaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEstadisticaCursoActionPerformed(evt);
            }
        });
        jMenu3.add(menEstadisticaCurso);

        menuBar.add(jMenu3);

        menNotasCurso.setText("Notas");

        jMenuItem2.setText("Ingresar Nota");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menNotasCurso.add(jMenuItem2);

        jMenuItem1.setText("Listado Notas por Curso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menNotasCurso.add(jMenuItem1);

        menuBar.add(menNotasCurso);

        jMenu4.setText("Instituto");

        menListadoInstituto.setText("Listado");
        menListadoInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListadoInstitutoActionPerformed(evt);
            }
        });
        jMenu4.add(menListadoInstituto);

        menInsertarInstituto.setText("Insertar");
        menInsertarInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInsertarInstitutoActionPerformed(evt);
            }
        });
        jMenu4.add(menInsertarInstituto);

        menActualizarInstituto.setText("Actualizar");
        menActualizarInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menActualizarInstitutoActionPerformed(evt);
            }
        });
        jMenu4.add(menActualizarInstituto);

        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menInsertarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menInsertarCursosActionPerformed
        FrmInsertaCurso frm = new FrmInsertaCurso();
        frm.setVisible(true);

    }//GEN-LAST:event_menInsertarCursosActionPerformed

    private void menListarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarProfesorActionPerformed
        FrmListadoProfesores frm = new FrmListadoProfesores();
        frm.setVisible(true);
    }//GEN-LAST:event_menListarProfesorActionPerformed

    private void menActualizarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menActualizarCursosActionPerformed
        FrmActualizaCurso frm = new FrmActualizaCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_menActualizarCursosActionPerformed

    private void menListadoCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListadoCursosActionPerformed
        FrmListadoCursos frm = new FrmListadoCursos();
        frm.setVisible(true);
    }//GEN-LAST:event_menListadoCursosActionPerformed

    private void menListadoInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListadoInstitutoActionPerformed
        FrmListadoIntitutos frm = new FrmListadoIntitutos();
        frm.setVisible(true);
    }//GEN-LAST:event_menListadoInstitutoActionPerformed

    private void menInsertarInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menInsertarInstitutoActionPerformed
        FrmInsertarInstituto frm = new FrmInsertarInstituto();
        frm.setVisible(true);
    }//GEN-LAST:event_menInsertarInstitutoActionPerformed

    private void menActualizarInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menActualizarInstitutoActionPerformed
        FrmActualizarInstituto frm = new FrmActualizarInstituto();
        frm.setVisible(true);
    }//GEN-LAST:event_menActualizarInstitutoActionPerformed

    private void menListadoEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListadoEstudiantesActionPerformed
        FrmListadoEstudiantes frm = new FrmListadoEstudiantes();
        frm.setVisible(true);

    }//GEN-LAST:event_menListadoEstudiantesActionPerformed

    private void menInsertarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menInsertarEstudiantesActionPerformed
        FrmInsertaEstudiante frm = new FrmInsertaEstudiante();
        frm.setVisible(true);
    }//GEN-LAST:event_menInsertarEstudiantesActionPerformed

    private void menActualizarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menActualizarEstudiantesActionPerformed
        FrmActualizarEstudiante frm = new FrmActualizarEstudiante();
        frm.setVisible(true);
    }//GEN-LAST:event_menActualizarEstudiantesActionPerformed

    private void menInsertarProfersorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menInsertarProfersorActionPerformed
        FrmInsertarProfesor frm = new FrmInsertarProfesor();
        frm.setVisible(true);
    }//GEN-LAST:event_menInsertarProfersorActionPerformed

    private void menActualizarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menActualizarProfesorActionPerformed
        FrmActualizarProfesor frm = new FrmActualizarProfesor();
        frm.setVisible(true);
    }//GEN-LAST:event_menActualizarProfesorActionPerformed

    private void menAsignarCursoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAsignarCursoProfesorActionPerformed
        FrmAsignarCursoProfesor frm = new FrmAsignarCursoProfesor();
        frm.setVisible(true);
    }//GEN-LAST:event_menAsignarCursoProfesorActionPerformed

    private void menListaoCursosProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListaoCursosProfesoresActionPerformed
        FrmListadoCursosProfesor frm = new FrmListadoCursosProfesor();
        frm.setVisible(true);
    }//GEN-LAST:event_menListaoCursosProfesoresActionPerformed

    private void menMatricularEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menMatricularEstudiantesActionPerformed
        FrmMatricularEstudiante frm = new FrmMatricularEstudiante();
        frm.setVisible(true);
    }//GEN-LAST:event_menMatricularEstudiantesActionPerformed

    private void menCursoEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCursoEstudiantesActionPerformed
        FrmListadoCursosAlumnos frm = new FrmListadoCursosAlumnos();
        frm.setVisible(true);
    }//GEN-LAST:event_menCursoEstudiantesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmListadoNotasCurso frm = new FrmListadoNotasCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmInsertarNota frm = new FrmInsertarNota();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menEstadisticaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEstadisticaCursoActionPerformed
        FrmEstadisticasCurso frm = new FrmEstadisticasCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_menEstadisticaCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menActualizarCursos;
    private javax.swing.JMenuItem menActualizarEstudiantes;
    private javax.swing.JMenuItem menActualizarInstituto;
    private javax.swing.JMenuItem menActualizarProfesor;
    private javax.swing.JMenuItem menAsignarCursoProfesor;
    private javax.swing.JMenuItem menCursoEstudiantes;
    private javax.swing.JMenuItem menEstadisticaCurso;
    private javax.swing.JMenuItem menInsertarCursos;
    private javax.swing.JMenuItem menInsertarEstudiantes;
    private javax.swing.JMenuItem menInsertarInstituto;
    private javax.swing.JMenuItem menInsertarProfersor;
    private javax.swing.JMenuItem menListadoCursos;
    private javax.swing.JMenuItem menListadoEstudiantes;
    private javax.swing.JMenuItem menListadoInstituto;
    private javax.swing.JMenuItem menListaoCursosProfesores;
    private javax.swing.JMenuItem menListarProfesor;
    private javax.swing.JMenuItem menMatricularEstudiantes;
    private javax.swing.JMenu menNotasCurso;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
