/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menListarProfesor = new javax.swing.JMenuItem();
        menInsertarProfersor = new javax.swing.JMenuItem();
        menActualizarProfesor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menListadoEstudiantes = new javax.swing.JMenuItem();
        menInsertarEstudiantes = new javax.swing.JMenuItem();
        menActualizarEstudiantes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menListadoCursos = new javax.swing.JMenuItem();
        menInsertarCursos = new javax.swing.JMenuItem();
        menActualizarCursos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menListadoInstituto = new javax.swing.JMenuItem();
        menInsertarInstituto = new javax.swing.JMenuItem();
        menActualizarInstituto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Profesores");

        menListarProfesor.setText("Listado");
        menListarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarProfesorActionPerformed(evt);
            }
        });
        jMenu1.add(menListarProfesor);

        menInsertarProfersor.setText("Insertar");
        jMenu1.add(menInsertarProfersor);

        menActualizarProfesor.setText("Actualizar");
        jMenu1.add(menActualizarProfesor);

        menuBar.add(jMenu1);

        jMenu2.setText("Estudiantes");

        menListadoEstudiantes.setText("Listado");
        jMenu2.add(menListadoEstudiantes);

        menInsertarEstudiantes.setText("Insertar");
        jMenu2.add(menInsertarEstudiantes);

        menActualizarEstudiantes.setText("Actualizar");
        jMenu2.add(menActualizarEstudiantes);

        menuBar.add(jMenu2);

        jMenu3.setText("Cursos");

        menListadoCursos.setText("Listado");
        menListadoCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListadoCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menListadoCursos);

        menInsertarCursos.setText("Insertar");
        menInsertarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menInsertarCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menInsertarCursos);

        menActualizarCursos.setText("Actualizar");
        menActualizarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menActualizarCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menActualizarCursos);

        menuBar.add(jMenu3);

        jMenu4.setText("Instituto");

        menListadoInstituto.setText("Listado");
        menListadoInstituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListadoInstitutoActionPerformed(evt);
            }
        });
        jMenu4.add(menListadoInstituto);

        menInsertarInstituto.setText("Insertar");
        jMenu4.add(menInsertarInstituto);

        menActualizarInstituto.setText("Actualizar");
        jMenu4.add(menActualizarInstituto);

        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menInsertarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menInsertarCursosActionPerformed
        InsertaCurso frm = new InsertaCurso();
        frm.setVisible(true);

    }//GEN-LAST:event_menInsertarCursosActionPerformed

    private void menListarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarProfesorActionPerformed

    }//GEN-LAST:event_menListarProfesorActionPerformed

    private void menActualizarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menActualizarCursosActionPerformed
        ActualizaCurso frm = new ActualizaCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_menActualizarCursosActionPerformed

    private void menListadoCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListadoCursosActionPerformed
        ListadoCursos frm = new ListadoCursos();
        frm.setVisible(true);
    }//GEN-LAST:event_menListadoCursosActionPerformed

    private void menListadoInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListadoInstitutoActionPerformed
        ListadoIntitutos frm = new ListadoIntitutos();
        frm.setVisible(true);
    }//GEN-LAST:event_menListadoInstitutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem menActualizarCursos;
    private javax.swing.JMenuItem menActualizarEstudiantes;
    private javax.swing.JMenuItem menActualizarInstituto;
    private javax.swing.JMenuItem menActualizarProfesor;
    private javax.swing.JMenuItem menInsertarCursos;
    private javax.swing.JMenuItem menInsertarEstudiantes;
    private javax.swing.JMenuItem menInsertarInstituto;
    private javax.swing.JMenuItem menInsertarProfersor;
    private javax.swing.JMenuItem menListadoCursos;
    private javax.swing.JMenuItem menListadoEstudiantes;
    private javax.swing.JMenuItem menListadoInstituto;
    private javax.swing.JMenuItem menListarProfesor;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
